version: '3.8'

services:
  web:
    build: .
    command: [ "gunicorn", "-b", "0.0.0.0", "-p", "8000", "SaaS_Boilerplate.wsgi:application" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
