version: '3.8'

services:
  web:
    build: .
    command: [ "daphne", "SaaS_Boilerplate.asgi:application", "--bind", "0.0.0.0", "--port", "8000" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  mqtt_listener:
    build: .
    command: [ "python", "manage.py", "runmqtt" ]
    volumes:
      - .:/app
