# Generated by Django 4.2.7 on 2023-12-14 18:16

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('mail', models.EmailField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, default='images/default/gvdRaw.png', null=True, upload_to='images/')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('end_subscription', models.DateField(blank=True, null=True)),
                ('neubit', models.BooleanField(blank=True, default=False, null=True)),
                ('clarify', models.BooleanField(blank=True, default=False, null=True)),
                ('bms', models.BooleanField(blank=True, default=False, null=True)),
                ('iot', models.BooleanField(blank=True, default=False, null=True)),
                ('cloudRecording', models.BooleanField(blank=True, default=False, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenant.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
