# Generated by Django 4.2.7 on 2023-12-15 05:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WS201',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('remaining', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selectIOT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ws201History', to='infrastructure.iotdevice')),
            ],
            options={
                'verbose_name_plural': 'Fill Level Sensor',
            },
        ),
        migrations.CreateModel(
            name='VS121',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('people_in', models.FloatField(blank=True, null=True)),
                ('people_out', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selectIOT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vs121History', to='infrastructure.iotdevice')),
            ],
            options={
                'verbose_name_plural': 'People Count Sensor',
            },
        ),
        migrations.CreateModel(
            name='UC512',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('valve_1', models.CharField(blank=True, max_length=10, null=True)),
                ('valve_1_pulse', models.CharField(blank=True, max_length=10, null=True)),
                ('valve_2', models.CharField(blank=True, max_length=10, null=True)),
                ('valve_2_pulse', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selectIOT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uc512History', to='infrastructure.iotdevice')),
            ],
            options={
                'verbose_name_plural': 'Solenoid Valve Controller',
            },
        ),
        migrations.CreateModel(
            name='GS301',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('h2s', models.FloatField(blank=True, null=True)),
                ('nh3', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selectIOT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gs301History', to='infrastructure.iotdevice')),
            ],
            options={
                'verbose_name_plural': 'Odor Sensor',
            },
        ),
        migrations.CreateModel(
            name='EM400',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selectIOT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='em400History', to='infrastructure.iotdevice')),
            ],
            options={
                'verbose_name_plural': 'Smart Bin Sensor',
            },
        ),
        migrations.CreateModel(
            name='EM300',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selectIOT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='em300History', to='infrastructure.iotdevice')),
            ],
            options={
                'verbose_name_plural': 'Zone Leakage Sensor',
            },
        ),
        migrations.CreateModel(
            name='AM319',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('co2', models.IntegerField(blank=True, null=True)),
                ('hcho', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('light_level', models.IntegerField(blank=True, null=True)),
                ('pir_trigger', models.CharField(blank=True, max_length=20, null=True)),
                ('pm10', models.IntegerField(blank=True, null=True)),
                ('pm2_5', models.IntegerField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('buzzer_status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selectIOT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='am319History', to='infrastructure.iotdevice')),
            ],
            options={
                'verbose_name_plural': 'Environment Sensor',
            },
        ),
    ]
